
import { Mentee, Request, Session } from "./types";


export const incomingRequests: Request[] = [
  {
    id:       'r1',
    student:  'Kwame Mensah',
    initials: 'KM',
    avatar:   '#185FA5',
    major:    'Computer Science',
    goal:     'Guidance on breaking into fintech after graduation',
    date:     '2 hours ago',
    status:   'PENDING',
  },
  {
    id:       'r2',
    student:  'Akosua Frimpong',
    initials: 'AF',
    avatar:   '#854F0B',
    major:    'Business Administration',
    goal:     'Preparing for PM interviews at big tech companies',
    date:     '1 day ago',
    status:   'PENDING',
  },
  {
    id:       'r3',
    student:  'Nana Acheampong',
    initials: 'NA',
    avatar:   '#0C5C3E',
    major:    'MIS',
    goal:     'Building a data engineering portfolio from scratch',
    date:     '3 days ago',
    status:   'PENDING',
  },
]

export const upcomingSessions: Session[] = [
  {
    id:       's1',
    title:    'CV and Portfolio Review',
    subtitle: 'Career planning session',
    student:  'Kwame Mensah',
    initials: 'KM',
    avatar:   '#185FA5',
    duration: '40 min',
    date:     'Today, 3:00 PM',
  },
  {
    id:       's2',
    title:    'Interview Preparation',
    subtitle: 'Mock interview + feedback',
    student:  'Akosua Frimpong',
    initials: 'AF',
    avatar:   '#854F0B',
    duration: '1h 00 min',
    date:     'Tomorrow, 10:00 AM',
  },
  {
    id:       's3',
    title:    'Networking Strategies',
    subtitle: 'Industry connections workshop',
    student:  'Esi Mensah',
    initials: 'EM',
    avatar:   '#9747FF',
    duration: '30 min',
    date:     'Wed, 2:00 PM',
  },
  {
    id:       's4',
    title:    'Salary Negotiation Tactics',
    subtitle: 'Offer evaluation walkthrough',
    student:  'Kofi Boateng',
    initials: 'KB',
    avatar:   '#0C5C3E',
    duration: '45 min',
    date:     'Thu, 11:00 AM',
  },
]

export const activeMentees: Mentee[] = [
  {
    id:       'm1',
    name:     'Kwame Mensah',
    major:    'Computer Science · 2024',
    initials: 'KM',
    avatar:   '#185FA5',
    industry: 'Technology',
    tag:      'yellow',
    progress: 60,
    sessions: 12,
    total:    20,
  },
  {
    id:       'm2',
    name:     'Akosua Frimpong',
    major:    'Business Admin · 2025',
    initials: 'AF',
    avatar:   '#854F0B',
    industry: 'Consulting',
    tag:      'purple',
    progress: 35,
    sessions: 7,
    total:    20,
  },
  {
    id:       'm3',
    name:     'Esi Mensah',
    major:    'MIS · 2024',
    initials: 'EM',
    avatar:   '#9747FF',
    industry: 'Finance',
    tag:      'green',
    progress: 80,
    sessions: 16,
    total:    20,
  },
]
